pipeline {
    agent any
    parameters{
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "Environment to Dpeloy", name: "deployEnv") 
        boolean(defaultValue: false, description: "Send Mail Post Deployment ?", name: "postMail")
        string(defaultValue: "Deployment success!", description: "Put custom mail message body text", name: "deployMessage")
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        /*stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }*/
        stage('Complete') {
            steps {
                echo "Build Completed !!!"
                echo "Build Info: ${deployEnv}, ${postMail}, ${deployMessage}"
            }
        }
    }
}
